module.exports = [
  {
    id: 1,
    img: 'https://i.ebayimg.com/00/s/NzY4WDEwMjQ=/z/fv8AAOSwm-ZaubXl/$_59.JPG',
    name: 'Mitsubishi LANCER ES FWD 2016 ',
    make: 'Mitsubishi',
    model: 'Lancer',
    year: 2016,
  },
  {
    id: 2,
    img: 'https://i.ebayimg.com/00/s/NTYwWDgwMA==/z/3WsAAOSwmOdaupPh/$_59.JPG',
    name: 'Dodge Charger 2013',
    make: 'Dodge',
    model: 'Charger',
    year: 2013,
  },
  {
    id: 3,
    img: 'https://i.ebayimg.com/00/s/NzY4WDEwMjQ=/z/ivYAAOSwol5Yyo-m/$_59.JPG',
    name: 'Chevrolet Corvette 2015 ',
    make: 'Chevrolet',
    model: 'Corvette',
    year: 2015,
  },
  {
    id: 4,
    img: 'https://i.ebayimg.com/00/s/NjAwWDEwMjQ=/z/93AAAOSwacVauZGK/$_35.JPG',
    name: 'Mercedes-Benz C-Class C 350 4MATIC NAVIGATION, PUSH BUTTON 2013',
    make: 'Mercedes-Benz',
    model: 'C-Class',
    year: 2013,
  },
  {
    id: 5,
    img: 'https://i.ebayimg.com/00/s/OTM2WDEyODA=/z/GH8AAOSwwB1aupK7/$_35.JPG',
    name: 'Audi S5 Convertible|Red Interior|Navigation 2013',
    make: 'Audi',
    model: 'S5',
    year: 2013,
  },
  {
    id: 6,
    img: 'https://i.ebayimg.com/00/s/ODAwWDgwMA==/z/lSQAAOSwy0JaKVqw/$_59.JPG',
    name: 'Smart Fortwo Coupe (2 door) 2010',
    make: 'Smart',
    model: 'Fortwo',
    year: 2010,
  },
  {
    id: 7,
    img: 'https://i.ebayimg.com/00/s/NDgwWDY0MA==/z/qG0AAOSw2PtauoKY/$_35.JPG',
    name: 'BMW Z4 M 2006',
    make: 'BMW',
    model: 'Z4 M',
    year: 2006,
  },
  {
    id: 8,
    img: 'https://i.ebayimg.com/00/s/ODAwWDYwMA==/z/dTIAAOSwPNNauoDd/$_35.JPG',
    name: 'Acura Integra Coupe 2000 - Etested Ready to GO! ',
    make: 'Acura',
    model: 'Integra',
    year: 2000,
  },
  {
    id: 9,
    img: 'https://www.cstatic-images.com/supersized/in/0f2629633580e995189c49867aff4509.jpg',
    name: 'BMW M3 Base 2015',
    make: 'BMW',
    model: 'M3 Base',
    year: 2015,
  },
  {
    id: 10,
    img: 'https://i.ebayimg.com/00/s/NzY4WDEwMjQ=/z/nwEAAOSwgLdaueM8/$_35.JPG',
    name: 'Honda Accord EX-L 2014 C0UPE AUT0 NAVI LEATHER SUNROOF 95K',
    make: 'Honda',
    model: 'Accord',
    year: 2014,
  },
];